// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMapSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMapSystem {
  error MapSystem_PlayerAlreadySpawned();

  function spawn(int32 x, int32 y) external;

  function diceRoll() external;

  function move() external;

  function addressToEntityKey(address addr) external pure returns (bytes32);
}
